# Generated by Django 3.2.23 on 2024-07-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='amount',
            new_name='_amount',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='_amount',
            field=models.IntegerField(db_column='amount', default=1),
        ),
    ]
